# Generated by Django 2.1.7 on 2019-03-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sclms', '0005_auto_20190227_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('campgDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sclms.CampaignDetails')),
            ],
        ),
        migrations.CreateModel(
            name='LocationChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=60)),
                ('campgDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sclms.CampaignDetails')),
            ],
        ),
        migrations.AddField(
            model_name='datacollectionchecklist',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sclms.LocationChecklist'),
        ),
    ]
