# Generated by Django 2.1.7 on 2019-03-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclms', '0006_auto_20190304_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacollectionchecklist',
            old_name='amount',
            new_name='dataAmount',
        ),
    ]
