# Generated by Django 2.1.7 on 2019-03-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclms', '0007_auto_20190304_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bid',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='bkash',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='empl_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='mar_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='nid',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cl',
            name='bid',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cl',
            name='bkash',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cl',
            name='empl_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cl',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cl',
            name='mar_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cl',
            name='nid',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agent',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='asign',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cl',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
