# Generated by Django 2.1.7 on 2019-03-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclms', '0008_auto_20190304_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='cl',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bid',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='nid',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='bid',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='nid',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
