# Generated by Django 2.1.7 on 2019-03-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclms', '0009_auto_20190306_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollectionchecklist',
            name='campgDetails',
        ),
        migrations.RemoveField(
            model_name='datacollectionchecklist',
            name='location',
        ),
        migrations.AddField(
            model_name='locationchecklist',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='DataCollectionChecklist',
        ),
    ]
