# Generated by Django 2.1.7 on 2019-03-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclms', '0010_auto_20190315_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationchecklist',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
